import type { BodyFamily } from "./types";
import type { DecorationZone } from "@/shared/contracts";

const barrelZone = (widthMm: number, heightMm: number, extra: Partial<DecorationZone> = {}): DecorationZone => ({
  id: "barrel",
  label: "Barrel",
  processes: ["engrave", "pad_print"],
  widthMm,
  heightMm,
  minTextHeightMm: 2,
  maxTextHeightMm: Math.min(4, heightMm),
  maxChars: 24,
  axialFraction: 0.42,
  angleDeg: 0,
  ...extra,
});

const capZone = (widthMm: number, heightMm: number, extra: Partial<DecorationZone> = {}): DecorationZone => ({
  id: "cap",
  label: "Cap",
  processes: ["engrave"],
  widthMm,
  heightMm,
  minTextHeightMm: 2,
  maxTextHeightMm: Math.min(3.5, heightMm),
  maxChars: 16,
  axialFraction: 0.78,
  angleDeg: 180,
  ...extra,
});

/**
 * Parker's current collections, grouped the way parkerpen.com groups them.
 * Dimensions and weights are published or measured retail figures rounded to the millimetre/gram;
 * they are illustrative until verified against physical samples (spec §18).
 */
export const FAMILIES: BodyFamily[] = [
  {
    id: "duofold",
    label: "Duofold Classic",
    tier: "Heritage",
    tagline: "The 1921 flagship. Precious resin, 18k nib, flat-top ends.",
    description:
      "Parker's most distinguished pen since 1921. Centennial proportions, precious resin body, ace-emblazoned 18-carat gold nib and the signature flat-top silhouette.",
    silhouette: {
      lengthMm: 138,
      barrelDiameterMm: 13.4,
      capDiameterMm: 14.2,
      capFraction: 0.44,
      tipTaper: 0.45,
      endStyle: "flat",
      clipStyle: "arrow",
      gripSeparate: true,
      capRings: 2,
      bodySplit: null,
      hoodedNib: false,
    },
    facts: { lengthMm: 138, barrelDiameterMm: 13.4, weightG: 34, mechanism: "Cap (screw)", material: "Precious resin, palladium or 23k gold trim", origin: "France" },
    zones: [barrelZone(40, 6, { maxChars: 20 }), capZone(22, 5)],
    gripFixed: true,
  },
  {
    id: "sonnet",
    label: "Sonnet",
    tier: "Classic",
    tagline: "Modern lines, traditional craft. The classic Parker profile.",
    description: "A slim, balanced classic available in lacquer, stainless steel and chiselled finishes with gold or palladium trim.",
    silhouette: {
      lengthMm: 134,
      barrelDiameterMm: 10.6,
      capDiameterMm: 12,
      capFraction: 0.45,
      tipTaper: 0.55,
      endStyle: "domed",
      clipStyle: "arrow",
      gripSeparate: true,
      capRings: 1,
      bodySplit: null,
      hoodedNib: false,
    },
    facts: { lengthMm: 134, barrelDiameterMm: 10.6, weightG: 27, mechanism: "Cap (pull) / twist ballpoint", material: "Brass body with lacquer or stainless steel" },
    zones: [barrelZone(38, 5), capZone(20, 4)],
    gripFixed: true,
  },
  {
    id: "parker51",
    label: "Parker 51",
    tier: "Classic",
    tagline: "The mid-century icon, reissued. Hooded nib, streamlined cap.",
    description: "The streamlined 1941 design with a hooded nib, precious resin barrel and a brushed steel or gold-plated cap.",
    silhouette: {
      lengthMm: 137,
      barrelDiameterMm: 11.5,
      capDiameterMm: 12.6,
      capFraction: 0.46,
      tipTaper: 0.7,
      endStyle: "rounded",
      clipStyle: "arrow",
      gripSeparate: false,
      capRings: 0,
      bodySplit: null,
      hoodedNib: true,
    },
    facts: { lengthMm: 137, barrelDiameterMm: 11.5, weightG: 24, mechanism: "Cap (pull)", material: "Precious resin barrel, stainless steel or gold-plated cap" },
    zones: [barrelZone(36, 5)],
    gripFixed: true,
  },
  {
    id: "ingenuity",
    label: "Ingenuity",
    tier: "Classic",
    tagline: "Contemporary and substantial. Chunky profile, bold clip.",
    description: "A wide, modern silhouette in matte and lacquered metal with a distinctive contemporary clip.",
    silhouette: {
      lengthMm: 141,
      barrelDiameterMm: 13,
      capDiameterMm: 14,
      capFraction: 0.47,
      tipTaper: 0.4,
      endStyle: "rounded",
      clipStyle: "modern",
      gripSeparate: true,
      capRings: 1,
      bodySplit: null,
      hoodedNib: false,
    },
    facts: { lengthMm: 141, barrelDiameterMm: 13, weightG: 46, mechanism: "Cap (pull)", material: "Brass body, lacquer or PVD finish" },
    zones: [barrelZone(42, 6), capZone(24, 5)],
    gripFixed: true,
  },
  {
    id: "urban",
    label: "Urban",
    tier: "Stylish",
    tagline: "Curved, contemporary, made for the city.",
    description: "A curved, ergonomic body with a bold modern clip and a twist ballpoint or capped fountain pen.",
    silhouette: {
      lengthMm: 136,
      barrelDiameterMm: 12,
      capDiameterMm: 13,
      capFraction: 0.42,
      tipTaper: 0.6,
      endStyle: "domed",
      clipStyle: "modern",
      gripSeparate: true,
      capRings: 1,
      bodySplit: null,
      hoodedNib: false,
    },
    facts: { lengthMm: 136, barrelDiameterMm: 12, weightG: 32, mechanism: "Cap (pull) / twist ballpoint", material: "Brass body with lacquer" },
    zones: [barrelZone(34, 5)],
    gripFixed: true,
  },
  {
    id: "im",
    label: "IM",
    tier: "Essential",
    tagline: "The everyday Parker. Tapered, reliable, endlessly giftable.",
    description: "A tapered, lightweight metal body in lacquer and brushed finishes with chrome or gold trim.",
    silhouette: {
      lengthMm: 137,
      barrelDiameterMm: 11,
      capDiameterMm: 12,
      capFraction: 0.46,
      tipTaper: 0.65,
      endStyle: "domed",
      clipStyle: "arrow",
      gripSeparate: false,
      capRings: 1,
      bodySplit: null,
      hoodedNib: false,
    },
    facts: { lengthMm: 137, barrelDiameterMm: 11, weightG: 26, mechanism: "Cap (pull) / twist ballpoint", material: "Brass body with lacquer or brushed metal" },
    zones: [barrelZone(36, 5), capZone(18, 4)],
    gripFixed: true,
  },
  {
    id: "jotter",
    label: "Jotter",
    tier: "Essential",
    tagline: "Since 1954. The click. The arrow. The steel.",
    description: "The original click ballpoint with a stainless steel cap and arrow clip, in steel or lacquered barrels.",
    silhouette: {
      lengthMm: 129,
      barrelDiameterMm: 9.5,
      capDiameterMm: 10,
      capFraction: 0.5,
      tipTaper: 0.75,
      endStyle: "rounded",
      clipStyle: "arrow",
      gripSeparate: false,
      capRings: 0,
      bodySplit: 0.5,
      hoodedNib: false,
    },
    facts: { lengthMm: 129, barrelDiameterMm: 9.5, weightG: 16, mechanism: "Push-button (click)", material: "Stainless steel cap; steel or lacquered barrel" },
    zones: [barrelZone(30, 4, { maxTextHeightMm: 3, maxChars: 18 })],
    gripFixed: true,
  },
  {
    id: "jotter_xl",
    label: "Jotter XL",
    tier: "Essential",
    tagline: "The Jotter, scaled up for a fuller grip.",
    description: "A larger-diameter Jotter with a lacquered barrel and matching cap.",
    silhouette: {
      lengthMm: 139,
      barrelDiameterMm: 10.5,
      capDiameterMm: 11,
      capFraction: 0.5,
      tipTaper: 0.75,
      endStyle: "rounded",
      clipStyle: "arrow",
      gripSeparate: false,
      capRings: 0,
      bodySplit: 0.5,
      hoodedNib: false,
    },
    facts: { lengthMm: 139, barrelDiameterMm: 10.5, weightG: 23, mechanism: "Push-button (click)", material: "Stainless steel cap; lacquered barrel" },
    zones: [barrelZone(34, 4.5, { maxChars: 20 })],
    gripFixed: true,
  },
  {
    id: "vector_xl",
    label: "Vector XL",
    tier: "Essential",
    tagline: "The starter Parker in metallic colours.",
    description: "A slim, lightweight metal-bodied pen in satin metallic finishes with chrome trim.",
    silhouette: {
      lengthMm: 138,
      barrelDiameterMm: 10,
      capDiameterMm: 11,
      capFraction: 0.44,
      tipTaper: 0.7,
      endStyle: "rounded",
      clipStyle: "plain",
      gripSeparate: true,
      capRings: 0,
      bodySplit: null,
      hoodedNib: false,
    },
    facts: { lengthMm: 138, barrelDiameterMm: 10, weightG: 18, mechanism: "Cap (pull)", material: "Metal body with satin metallic lacquer" },
    zones: [barrelZone(32, 4.5)],
    gripFixed: true,
  },
];

export const familyById = (id: string) => FAMILIES.find((f) => f.id === id);
